#!/bin/bash

if [[ `cat ${THEME_PATH}theme.value` == "0" ]]; then  # If the theme is the light theme.
   /bin/sh -c "LD_LIBRARY_PATH=$BEMENU_PATH BEMENU_RENDERERS=$BEMENU_PATH $BEMENU_PATH/bemenu-run -p bemenu --fn \"Proggy Vector Dotted 12\" --border 2 --prefix -- --margin 100 --center --fixed-height --counter always --list \"10 up\" --single-instance --tb \"#000000\" --tf \"#ffffff\" --fb \"#ffffff\" --ff \"#000000\" --nb \"#ffffff\" --nf \"#000000\" --hb \"#ffffff\" --hf \"#005e8b\" --fbb \"#ffffff\" --fbf \"#000000\" --sb \"#ffffff\" --sf \"#000000\" --ab \"#ffffff\" --af \"#000000\" --scb \"#ffffff\" --scf \"#000000\" --bdr \"#000000\""  # TODO: Spread this out to multiple lines.
elif [[ `cat ${THEME_PATH}theme.value` == "1" ]]; then  # If the theme is the dark theme.
     /bin/sh -c "LD_LIBRARY_PATH=$BEMENU_PATH BEMENU_RENDERERS=$BEMENU_PATH $BEMENU_PATH/bemenu-run -p bemenu --fn \"Proggy Vector Dotted 12\" --border 2 --prefix -- --margin 100 --center --fixed-height --counter always --list \"10 up\" --single-instance --tb \"#ffffff\" --tf \"#000000\" --fb \"#000000\" --ff \"#ffffff\" --nb \"#000000\" --nf \"#ffffff\" --hb \"#000000\" --hf \"#00d3d0\" --fbb \"#000000\" --fbf \"#ffffff\" --sb \"#000000\" --sf \"#ffffff\" --ab \"#000000\" --af \"#ffffff\" --scb \"#000000\" --scf \"#ffffff\" --bdr \"#ffffff\""
fi
