#!/bin/bash

Xephyr -br -ac -noreset -screen 600x450 :13 &
export DISPLAY=:13
sleep 3

setxkbmap -layout us -variant dvp -option ctrl:swapcaps

python /home/lucas/programming/misc/bots/brawlhalla/v1.0/brawlhalla.py
